version: "3.9"

services:
  redis:
    image: redis:6
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  migration:
    build: .
    image: migration
    command: python manage.py migrate
    volumes:
      - .:/code