# Generated by Django 3.2.9 on 2021-11-09 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('increase_percentage', models.IntegerField(default=None, null=True)),
                ('destination_team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_set', to='game.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('source_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_set', to='game.team')),
            ],
        ),
    ]
